<?xml version="1.0" encoding="utf-8"?><Database Name="Cars_Dealership" Class="dbChartSalesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8NCC9GI\SQLEXPRESS;Initial Catalog=Cars_Dealership;Integrated Security=True" SettingsObjectName="Cars_Dealership_DBProject.Properties.Settings" SettingsPropertyName="Cars_DealershipConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.viewSales" Member="viewSales">
    <Type Name="viewSale">
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sales" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>